### ISSUE TITLE
mod_url relics in the code

### ISSUE THREAD

**Issue by mudrd8mz** [center-for-learning-management/moodle-mod_msteams#1]
I understood from the code and the README description that the mod_url module has been used as a base for the development. However, I noticed there are a few places that still refer to the URL module functionality even if there is no real point for it any more. I think it deserves some cleanup to make the code readable.

Examples include:

* The view.php accepting the `$u` parameter (with the "URL instance id" comment)
* The view.php creates the `$url` variable to hold the instance of the "msteams" module.
* Excessive and useless usage of the mod_url logic such as 
```
$displaytype = RESOURCELIB_DISPLAY_EMBED;
if ($displaytype == RESOURCELIB_DISPLAY_OPEN) {
    $redirect = true;
}
```
etc.

**Comment by rschrenk** [comment]
I have gone through the code, renamed variables accordingly and removed obsolete code
commit be72e5560473e594d9766755fee971b08cc2a0b6
