### ISSUE TITLE
Receive 404 response when submitting New Meeting form

### ISSUE THREAD

**Issue by geoffreyvanwyk** [center-for-learning-management/moodle-mod_msteams#12]
On the mod_form, after signing into Teams, filling out the New Meeting form, then clicking "Create", I receive a 404 response in the iframe.

When looking at the Network tab of Chrome Dev Tools, the request is made to the following path: **/lib/editor/atto/plugins/teamsmeeting/result.php**. It seems this plug-in depends on the Atto plug-in: https://moodle.org/plugins/atto_teamsmeeting because it works after installing it.

**Comment by rschrenk** [comment]
Hello,
thank you for that info. I added editor_atto and atto_teamsmeeting as dependencies.
Kind regards
