### ISSUE TITLE
Creating cookies every seconds

### ISSUE THREAD

**Issue by azmatksa** [center-for-learning-management/moodle-mod_msteams#14]
Hi, 

We noticed the mod/msteams/cookies.php creating a separate cookie in every seconds, how can we fix it?

![image](https://user-images.githubusercontent.com/49816686/154058525-017ce647-09e6-45b9-babe-c00bb34afb3e.png)

**Comment by rschrenk** [comment]
This is due to https://github.com/center-for-learning-management/moodle-mod_msteams/issues/13#issuecomment-1017724733

Please read there about the reasons. Currently, I have no other possibility to fix that issue.

**Comment by azmatksa** [comment]
Hi, 
Thank you for point out the reason. 

We noticed the Samesite=None, but still cookies are creating and also the meeting URL still blank during creating the meeting instance in Moodle.

**Comment by rschrenk** [comment]
Are you running the site under HTTPS?

**Comment by azmatksa** [comment]
Yes we're using HTTPS!

**Comment by rschrenk** [comment]
I am sorry, I cannot reproduce it.
