### ISSUE TITLE
Unable to save the mod_form

### ISSUE THREAD

**Issue by mudrd8mz** [center-for-learning-management/moodle-mod_msteams#2]
I can't create a new instance of the module. I am constantly redirected back to the setting form (mod_form) but no field is marked with validation failure.

**Comment by rschrenk** [comment]
have you set up the URL of the ms teams meeting app in the website administration?
https://github.com/OfficeDev/msteams-app-lms-meetings#frequently-asked-questions

**Comment by rschrenk** [comment]
Hi Dave,
I assume this was due to the fact, that there was not url created. The text field was invisible, so you have not seen the error message. Now the text field is displayed, but not editable. Therefore an appropriate error message should appear.
commit d24fdf695951492d28456178027211f711d948eb
