### ISSUE TITLE
Where can I specify the MS Teams URL when creating a new instance?

### ISSUE THREAD

**Issue by mudrd8mz** [center-for-learning-management/moodle-mod_msteams#3]
In other words, how can I specify the per-instance `externalurl` value?

**Comment by rschrenk** [comment]
Dear Dave,

it is the purpose of this plugin, that you do not specify the URL on your own. You could always create the teams invitation link in MS Teams itself, and add it to a course using the url module. The purpose of this plugin is, that it utilizes the teams meeting app (https://github.com/OfficeDev/msteams-app-lms-meetings).

When you add this module you only see an iframe that embeds this teams meeting app. This app is also used by the atto plugin (https://moodle.org/plugins/atto_teamsmeeting), from where I got the idea.

As soon as the invitation url is display inside the iframe it is grabbed by a JavaScript, the iframe gets hidden and the url is set in the invisible url-field of the form. Therefore you never see the invitation link itself.

Kind regards

**Comment by rschrenk** [comment]
The URL-Field is now displayed in a disabled text field
commit d24fdf695951492d28456178027211f711d948eb
